# config/pretrain.yaml
Pretrain:
  task: temporal                 # temporal / spatial / tem&spa

# Dataset Registry
Active_dataset:
  SL_datasets: ["CSL_Daily", "CSL_News"]
  SL_weights: [1.0, 1.5]
  SL_noise_datasets: ["something-something-v2"]
  SL_noise_weights: [1]
  BG_datasets: ["UCF101", "something-something-v2"]
  BG_weights: [1.0, 0.25]

# Synthetic World
synthetic_method: config/synthetic/syn1.yaml

# trainer
#  train_split: train
#  eval_split:  test

# Data Settings
data:
  resize: [112, 112]
  channel: 3  # 1 or 3
  augment: config/augment/a1.yaml

datasets:
  CSL_Daily: /home/pxl416/PeixiLiu/px_proj/Uni-SLM/config/dataset/CSL-Daily.yaml
  CSL_News: config/dataset/CSL-News.yaml
  BOBSL: config/dataset/BOBSL.yaml
  UCF101: config/dataset/UCF101.yaml

# Model
model: config/model/m2.yaml

# Save & Logging
save_dir: /home/pxl416/PeixiLiu/px_proj/Uni-SLM/checkpoints/pretrainer/temporal

wandb:
  use: true
  project: unisle-pttest-12  # uni-slm-finetuner
  run_name: pt-tem-260104

seed: 3407