# CSL-Daily Dataset Configuration

dataset:
  modalities:
    rgb: true
    pose: false
    text: true

  paths:
    root: /home/pxl416/PeixiLiu/px_proj/px_data/csl-daily-frames-512x512 # /home/pxl416/PeixiLiu/px_proj/Uni-SLM/data/mini_CSL_Daily
#    root: /home/pxl416/PeixiLiu/px_proj/Uni-SLM/data/mini_CSL_Daily
    rgb: sentence
    pose: null
    text: sentence_label/csl2020ct_v2.pkl
    segments: sentence_label/video_map.txt

  splits:
    train: sentence_label/split_1_train.txt
    dev:   sentence_label/split_1_dev.txt
    test:  sentence_label/split_1_test.txt


# Dataset-level Augmentation (覆盖 global，不受 task 影响)

